version: '3.8'

services:
  # Vehicle Price Prediction API
  vehicle-price-api:
    build: .
    container_name: vehicle-price-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models:ro
      - ./outputs:/app/outputs:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vehicle-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: vehicle-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vehicle-price-api
    restart: unless-stopped
    networks:
      - vehicle-network

  # Streamlit dashboard (optional)
  streamlit-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: vehicle-streamlit
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models:ro
      - ./outputs:/app/outputs:ro
    restart: unless-stopped
    networks:
      - vehicle-network
    profiles:
      - dashboard

networks:
  vehicle-network:
    driver: bridge

volumes:
  model-data:
    driver: local
